package v4;

import v4.domain.Position;
import v4.read.InMemoryReadModel;
import v4.write.*;

// Demo class to demonstrate the usage of the command handler for executing commands related to vehicle creation,
// movement, and removal, and to show the resulting events produced by these commands.
public class DemoCommands {
    public static void main(String[] args) throws Exception {

        // In-memory event producer to capture the events generated by the command handler for demonstration purposes.
        InMemoryEventProducer producer = new InMemoryEventProducer();

        // Event store repository that uses the in-memory event producer to store events, and an aggregate loader that can load the current state of vehicle aggregates based on the stored events.
        EventStoreRepository eventStore = new EventStoreRepository(producer);
        VehicleAggregateLoader loader = new VehicleAggregateLoader(eventStore);

        // In-memory read model to be used by the command handler for checking the current state of vehicles when executing commands.
        InMemoryReadModel readModel = new InMemoryReadModel();

        // Command handler that uses the event producer to send commands and the aggregate loader to load the current state of the vehicle aggregates.
        IVehicleCommands commands = new VehicleCommandHandler(producer, loader, readModel);

        commands.createVehicle("car1", new Position(0, 0));
        commands.moveVehicle("car1", new Position(1, 0));
        commands.moveVehicle("car1", new Position(0, 2));
        commands.removeVehicle("car1");

        producer.getEvents().forEach(System.out::println);
    }
}
